--- # Global --------------------------

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - lint
  - test
  - deploy

# Jobs templates ------------------

.install-deps-template: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv

.lint-template: &lint
  <<: *install-deps
  image: python:3.7
  stage: lint

.test-template: &test
  <<: *install-deps
  image: python:3.7
  stage: test
  script:
    - make snakemake flags="--directory .test" || (for f in .test/logs/*; do echo $f; cat $f; done; for f in .test/logs/*/*; do echo $f; cat $f; done; exit 1)
    - make report flags="--directory .test"
    - mkdir public
    - mv .test/report.html public/index.html
  artifacts:
    paths:
      - public
    when: always
    expire_in: 1 week

# Lint jobs ----------------------

pre-commit:
  <<: *lint
  script: make pre-commit

# Tests jobs ------------------------

test_workflow:
  <<: *test
  except:
    - master

pages:
  <<: *test
  stage: deploy
  only:
    - master
