# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

samples: config/samples.tsv
units: config/units.tsv

#########################
# Cookiecutter Examples #
#########################
resources:
  ref:
    transcriptome: "resources/ref/Homo_sapiens.GRCh38.cdna.chr21.fa"
    # species needs to be an identifier known to biomart, e.g. mmusculus, hsapiens
    species: hsapiens
  ontology:
    # gene ontology to download, used e.g. in goatools
    gene_ontology: "http://current.geneontology.org/ontology/go-basic.obo"
